spring:
  application:
    name: ${MOVIE_REVIEW_APPLICATION_NAME:MovieReviewService}
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/all-about-movies?authSource=admin
      host: localhost
      port: 27017
      database: all-about-movies
      username: admin
      password: admin

server:
  port: ${MOVIE_REVIEW_APPLICATION_PORT:8081}

logging:
  pattern:
    console: ${MOVIE_REVIEW_CONSOLE_LOGGING_PATTERN:%green(%d{yyyy-MM-dd HH:mm:ss}) %blue(%-5level) %red([%thread]) %yellow(%logger{36}) - %msg%n}
  level:
    root: info
    org.springframework.web: debug
    org.springframework.reactive: debug
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: debug

